# Related configuration instructions
  # favicon: Website icon
  # avatar: Theme user avatar and nickname
  # rss: rss
  # prevnext: Previous and next pages at the end of the article
  # footer: Footer information
  # search: Article search

# enable: Whether to enable the corresponding function, optional true || false

# Website icon
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# User avatar and nickname
avatar:
  author_photo: /images/avatar.png
  author_nickname: Rui Ramos 
  path: /

# Previous and next pages at the end of the article
prevnext:
  enable: true

# Link Information
link: 
  # name: name
  # icon: Icon, currently only supports some icons of IconFont
  # path: path
  # target: target
  -
    # 档案
    name: archives
    icon: bookmark
    path: /archives/
  -
    name: github
    icon: github
    path: https://github.com/rramos
    target: _blank
  -
    name: email
    icon: envelope
    path: mailto:rui.ms.ramos@gmail.com
  -
    name: twitter
    icon: twitter
    path: https://x.com/RuiMSRamos
  -
    name: about
    icon: qq 
    path: /about
  -
    name: discord
    icon: wechat
    path: https://discord.gg/YfCmqpG53p 
  -
    # rss - hexo-generator-feed 
    # - https://github.com/hexojs/hexo-generator-feed
    name: rss
    icon: rss
    path: /atom.xml
    target: _blank


# Footer Information
footer:
  -
    name: Copyright © Rui Ramos 2024
    path: https://github.com/rramos

# Article search
search:
  enable: true
  placeholder: 

# Google Analytics
ga4:
  enable: false
  id: G-6VMKQTVJC2

# Google Tag Manager
tagmanager:
  enable: true
  id: GTM-MXRC4DK

# GoogleCrux
googlecrux:
  enable: true
  id: "Em0OaYgLD4MC3tIHbwqDxAklIn7JzrtipNZd7z1kqFI"

# Klaro Consent form
consent:
  enable: true

# Newsletter Subscription
newsletter:
  enable: false

# MS Clarity
clarity:
  enable: true
  id: ms0b2q35b6

# Webpushr
webpushr:
  enable: true
  id: BGON3evm0aCcG-ZpkVez8Q8GLrn4527R6YkL4nsU861337AfhJoOvnVU7eJ6ixjspxhic7ecVXvnhGgJz0cfDrE