# 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # prevnext: 文章末尾的上一页与下一页
  # footer: 页脚信息
  # search: 文章搜索

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: false
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# 用户头像与昵称
avatar:
  author_photo: /images/rramos-avatar.png
  author_nickname: rramos.github.io 
  path: /

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 链接信息
link: 
  # name: 名称
  # icon: 图标，目前仅支持IconFont部分图标
  # path: 地址
  # target: 跳转方式
  -
    # 档案
    name: archives
    icon: bookmark
    path: /archives/
  -
    name: github
    icon: github
    path: https://github.com/rramos
    target: _blank
  -
    name: email
    icon: envelope
    path: mailto:rui.ms.ramos@gmail.com
  -
    name: twitter
    icon: twitter
    path: https://x.com/RuiMSRamos
  -
    name: about
    icon: qq 
    path: /about
  -
    name: discord
    icon: wechat
    path: https://discord.gg/YfCmqpG53p 
  -
    # rss需安装 hexo-generator-feed 插件
    # 具体参照https://github.com/hexojs/hexo-generator-feed
    name: rss
    icon: rss
    path: /atom.xml
    target: _blank


# 页脚信息
footer:
  -
    name: Copyright © Rui Ramos 2024
    path: https://github.com/rramos

# 文章搜索
search:
  enable: true
  placeholder: 

# Added GA4 Configuration
ga4:
  enable: false
  id: G-6VMKQTVJC2

tagmanager:
  enable: true
  id: GTM-MXRC4DK

googlecrux:
  enable: true
  id: "Em0OaYgLD4MC3tIHbwqDxAklIn7JzrtipNZd7z1kqFI"

consent:
  enable: true

newsletter:
  enable: false  